In [18]:
import matplotlib.pyplot as plt
import numpy as np

In [19]:
def printMeaningful(value, sigma=0.0):
    tennage = 0
    if sigma == 0:
        sigma = value
    while sigma < 1:
        tennage -= 1
        sigma *= 10
        value *= 10
    while sigma > 10:
        tennage += 1
        sigma /= 10
        value /= 10
    print( "({:.1f} \pm {:.1f}) \cdot 10^{}{}{}".format(value, sigma, "{", tennage, "}"))

In [20]:
class obj:
  pass

In [21]:
materials = {"copper":obj(), "steel":obj(), "dura":obj()}

# Samples

In [22]:
for i in materials:
    print(i)
    materials[i].d = []
    with open(f"samples/{i}", "r") as file:
        print(file.readline())
        materials[i].L, materials[i].sigma_L = (
            float(i) for i in file.readline().strip().split())
        print(file.readline())
        materials[i].m, materials[i].sigma_m = (
            float(i) for i in file.readline().strip().split())
        print(file.readline())
        materials[i].instrum_d = (float(file.readline().strip()))
        print(file.readline())
        for line in file:
            materials[i].d.append(float(line.strip()))
        materials[i].d = np.array(materials[i].d)
    print(materials[i].d)

copper
L sigma_L

m sigma_m

sigma_d

d

[12.11 12.1  12.11 12.11 12.11]
steel
L sigma_L

m sigma_m

sigma_d

d

[12.03 12.02 12.11 12.24 12.26]
dura
L sigma_L

m sigma_m

sigma_d

d

[11.74 11.75 11.91 11.96 11.96]


In [23]:
materials["steel"].d

array([12.03, 12.02, 12.11, 12.24, 12.26])

In [24]:
for i in range(5):
  print("\t\t\t\t\hline\n\t\t\t\t", end = "")
  print("{}&{}&{}\\\\".format(materials["copper"].d[i], materials["steel"].d[i], materials["dura"].d[i]))

				\hline
				12.11&12.03&11.74\\
				\hline
				12.1&12.02&11.75\\
				\hline
				12.11&12.11&11.91\\
				\hline
				12.11&12.24&11.96\\
				\hline
				12.11&12.26&11.96\\
